# Generated by Django 4.2.27 on 2026-01-21 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Capacité maximale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Classe active')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['level__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du niveau')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du niveau')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Année scolaire')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Année active')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code de la matière')),
                ('coefficient', models.PositiveIntegerField(default=1, verbose_name='Coefficient')),
                ('is_active', models.BooleanField(default=True, verbose_name='Matière active')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Professeur actif')),
                ('subjects', models.ManyToManyField(blank=True, to='core.subject', verbose_name='Matières enseignées')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Professeur',
                'verbose_name_plural': 'Professeurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Élève actif')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du père')),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la mère')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone parent')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='Email parent')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.class', verbose_name='Classe actuelle')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level', verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='class',
            name='main_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher', verbose_name='Professeur principal'),
        ),
        migrations.AddField(
            model_name='class',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear', verbose_name='Année scolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'school_year')},
        ),
    ]
