# Generated by Django 4.2.27 on 2026-01-22 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='reportcard_type',
            field=models.CharField(choices=[('primary', 'Primaire'), ('secondary', 'Secondaire'), ('higher', 'Supérieur')], default='primary', max_length=20, verbose_name='Type de bulletin'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialty',
            field=models.CharField(choices=[('mathematiques', 'Mathématiques'), ('francais', 'Français'), ('histoire', 'Histoire-Géographie'), ('sciences', 'Sciences de la Vie et de la Terre'), ('physique', 'Physique-Chimie'), ('anglais', 'Anglais'), ('education_civique', 'Éducation Civique'), ('arts_plastiques', 'Arts Plastiques'), ('musique', 'Éducation Musicale'), ('eps', 'Éducation Physique')], default='francais', max_length=50, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
