# Generated by Django 4.2.27 on 2026-01-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_level_reportcard_type_teacher_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
