# Generated by Django 4.2.27 on 2026-01-21 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la période')),
                ('number', models.PositiveIntegerField(choices=[(1, '1er Trimestre'), (2, '2ème Trimestre'), (3, '3ème Trimestre')], verbose_name='Numéro de trimestre')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Période active')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
                'ordering': ['school_year', 'number'],
                'unique_together': {('number', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('TRIMESTRIEL', 'Bulletin trimestriel'), ('ANNUEL', 'Bulletin annuel')], max_length=20, verbose_name='Type de bulletin')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne générale')),
                ('class_ranking', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang dans la classe')),
                ('class_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Effectif de la classe')),
                ('teacher_comments', models.TextField(blank=True, verbose_name='Appréciation du professeur principal')),
                ('director_comments', models.TextField(blank=True, verbose_name='Appréciation du directeur')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('is_final', models.BooleanField(default=False, verbose_name='Bulletin définitif')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schoolyear', verbose_name='Année scolaire')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Élève')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.term', verbose_name='Période (pour bulletins trimestriels)')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'school_year', 'term', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne de la matière')),
                ('coefficient', models.PositiveIntegerField(default=1, verbose_name='Coefficient')),
                ('appreciation', models.TextField(blank=True, verbose_name='Appréciation')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.reportcard', verbose_name='Bulletin')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Professeur de la matière')),
            ],
            options={
                'verbose_name': 'Note par matière',
                'verbose_name_plural': 'Notes par matière',
                'unique_together': {('report_card', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('CONTROLE', 'Contrôle'), ('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('PARTICIPATION', 'Participation'), ('COMPORTEMENT', 'Comportement')], default='CONTROLE', max_length=20, verbose_name='Type de note')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note (/20)')),
                ('coefficient', models.PositiveIntegerField(default=1, verbose_name='Coefficient')),
                ('max_points', models.DecimalField(decimal_places=2, default=20, max_digits=4, verbose_name='Points maximum')),
                ('date', models.DateField(verbose_name='Date de la note')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Élève')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject', verbose_name='Matière')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Professeur')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.term', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-date', 'student', 'subject'],
                'unique_together': {('student', 'subject', 'date', 'grade_type')},
            },
        ),
    ]
